version: 0.6.0.20
branches:
  only:
  - master
image: Visual Studio 2017
configuration:
  - Release
  - ReleaseAVX2
platform:
  - x64
install:
  - ps: appveyor DownloadFile http://thecrewchief.org/downloads/appveyor/ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: 7z x -olibs/libovr ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: ./configure.cmd
before_build:
  - nuget restore
build:
  project: OpenOVR.sln
  verbosity: minimal
on_success:
- ps: >-

    pushd ./x64/$env:Configuration/
     
    7z a ../../OpenComposite_tiwm_$env:APPVEYOR_BUILD_VERSION"_"$env:Configuration.zip "openvr_api.dll"
    
    popd
    
    pushd ./res/
    
    dir
    
    7z a ../OpenComposite_tiwm_$env:APPVEYOR_BUILD_VERSION"_"$env:Configuration.zip "opencomposite.ini"
    
    7z a ../OpenComposite_tiwm_$env:APPVEYOR_BUILD_VERSION"_"$env:Configuration.zip "readme.txt"
    
    popd
    
    Push-AppveyorArtifact OpenComposite_tiwm_$env:APPVEYOR_BUILD_VERSION"_"$env:Configuration.zip