version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform:
  - Win32
  - x64
install:
  - cmd: >-
      git submodule update --init --recursive
  - ps: appveyor DownloadFile https://znix.xyz/random/vulkan-1.1.85.0-minisdk.7z
  - ps: 7z x -olibs vulkan-1.1.85.0-minisdk.7z
  - ps: ./configure.cmd
before_build:
  - ps: >-
      mkdir build;
      cd build

      # It's either x64 or Win32
      cmake .. -A $env:Platform

      cd ..
build:
  project: build/OpenComposite.sln
  verbosity: minimal
on_success:
- ps: >-
    Push-AppveyorArtifact "build/$env:Configuration/OCOVR.dll" -FileName "$env:Platform/openvr_api.dll"

    7z a OpenComposite.zip "RuntimeSwitcher/bin/$env:Configuration"

    7z rn OpenComposite.zip "RuntimeSwitcher/bin/$env:Configuration" "OpenComposite"

    Push-AppveyorArtifact "OpenComposite.zip"
