version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform:
  - x64
install:
  - ps: appveyor DownloadFile http://thecrewchief.org/downloads/appveyor/ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: appveyor DownloadFile http://thecrewchief.org/downloads/appveyor/vulkan-1.1.85.0-minisdk.7z
  - ps: 7z x -olibs/libovr ovr_sdk_win_1.26.0_public_nosamples.7z
  - ps: 7z x -olibs vulkan-1.1.85.0-minisdk.7z
  - ps: ./configure.cmd
before_build:
  - nuget restore
build:
  project: OpenOVR.sln
  verbosity: normal
on_success:
- ps: >-
    $effective_plat = $env:Platform
    Push-AppveyorArtifact "$effective_plat/$env:Configuration/openvr_api.dll" -FileName "$env:Platform/openvr_api.dll"

    7z a OpenComposite.zip "RuntimeSwitcher/bin/$env:Configuration"

    7z rn OpenComposite.zip "RuntimeSwitcher/bin/$env:Configuration" "OpenComposite"

    Push-AppveyorArtifact "OpenComposite.zip"
