version: '{build}'

platform:
  - x86
  - x64

configuration:
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: ON

before_build:
  - cmake .

build_script:
  - cmake --build . --config %CONFIGURATION%
